# -*- coding: utf-8 -*-
"""Myclient.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/122MidUlqGugm686Ian3MmSGxhfK30Ovb
"""

import socket             
s = socket.socket()       
port = 12345                
s.connect(('127.0.0.1', port))  

print (s.recv(1024) ) 
# close the connection  
s.close()

